spring:
  application:
    name: ezra-repayment-api

server:
  port: 8080

default:
    loan:
      months: 1

proc:
  scheduler: "*/20 * * * * *"

twilio:
  account_sid: x
  auth_token: 8523393b4e26e4b1060add81becca559
  trial_number: +19125757746

loan:
  multiple-lending-allowed: true